### ISSUE TITLE
Service error on Ubuntu 14.04

### ISSUE THREAD

**Issue by bshow80** [razorsedge/puppet-openvmtools#1]
I receive this error every time I run "puppet agent --test" and the open-vm-tools service is running already.

Error: Could not start Service[open-vm-tools]: Execution of '/etc/init.d/open-vm-tools start' returned 1: * Starting open-vm daemon vmtoolsd
Error: /Stage[main]/Openvmtools/Service[open-vm-tools]/ensure: change from stopped to running failed: Could not start Service[open-vm-tools]: Execution of '/etc/init.d/open-vm-tools start' returned 1: * Starting open-vm daemon vmtoolsd

**Comment by razorsedge** [comment]
What version of operating system, Open VM Tools, and Puppet are you using?

**Comment by bshow80** [comment]
Unbuntu 14.04 Server
Puppet 3.7.5
Open VM Tools 2:9.4.0-1280544-5ubuntu6.2

**Comment by razorsedge** [comment]
And I should have read the title of the issue to know one of those answers... :-(

Try passing the parameter `service_hasstatus => true` in the main class.
```puppet
class { '::openvmtools':
  service_hasstatus => true,
}
```

**Comment by bshow80** [comment]
I am still receiving

Error: Could not start Service[open-vm-tools]: Execution of
'/etc/init.d/open-vm-tools start' returned 1: * Starting open-vm daemon
vmtoolsd
Error: /Stage[main]/Openvmtools/Service[open-vm-tools]/ensure: change from
stopped to running failed: Could not start Service[open-vm-tools]:
Execution of '/etc/init.d/open-vm-tools start' returned 1: * Starting
open-vm daemon vmtoolsd

although the service is in fact running.

**Comment by razorsedge** [comment]
I have pushed version 1.0.0 to the Puppet Forge.  Please let me know if this fixes the problem.

**Comment by bshow80** [comment]
Mike,

This seems to have fixed it. Thank you!
